name: buildingtheclubhouse
favicon: null
layout_spectrum: 0.65798
typography_spectrum: 0.52719
title: Work and Mental Health Recovery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5903909895569086
  lightness: 0.047125377459451556
  saturation: 0.25
  rhythmicContrast: 0.18386328290216625
purpose: []
